### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by web-dave** [web-dave/bookmonkey-client#1]
```scss
body {
  background-color: darkslategray;
  color: lightcyan;
  .list {
    display: grid;
    place-content: center;
    router-outlet {
      margin-top: 50px;
    }
    app-book {
      div {
        width: 600px;
      }
      app-book-card {
        display: block;
        background-color: rgb(50, 99, 99);
        box-shadow: 5px 5px 15px -2px lightcyan;
        border: 3px solid lightcyan;
        border-radius: 15px;
        padding: 15px;
        margin-top: 15px;
        margin-bottom: 5px;
        width: 100%;
        p {
          border-radius: 15px;
          padding: 15px;
        }
      }
    }
  }
}
```
